#!/bin/sh
## PRE SETUP
#fuser -cuk /var/lib/dpkg/lock
#rm -f /var/lib/dpkg/lock

postinstdir=/tmp/client
#clean
rm -rf $postinstdir
mkdir -p $postinstdir


PLATFORM_LINUX_BLUEGIGA="Bluegiga"
PLATFORM_LINUX_DREAMPLUG="Dreamplug"
PLATFORM_LINUX_DDWRT="DDWRT"
PLATFORM_MAC="MacOSX"
PLATFORM_UNKNOWN="Unknown"

if [ -d  /etc/bluegiga-release ]; then
  echo "$PLATFORM_LINUX_BLUEGIGA"
elif [ -f  /etc/rc.local ]; then
  echo "$PLATFORM_LINUX_DREAMPLUG"
elif [ -d  /jffs ]; then
  echo "$PLATFORM_LINUX_DDWRT"
elif [ -d  /Library ]; then
  echo "$PLATFORM_MAC"
else
  echo "$PLATFORM_UNKNOWN"
fi



exit 0
